### Login
# POST https://autobilling.backend.vibevaulttech.co.in/loginUser
POST http://localhost:8000/loginUser
Content-Type: application/json

{
  "email": "ohmvaghela1@gmail.com",
  "password": "ohm123ohm"
}

### Signup
POST http://localhost:8000/addUser
Content-Type: application/json

{
  "shopName": "req.body.name",
  "firstName": "req.body.firstname",
  "lastName": "req.body.lastname",
  "shopEmail": "req.body.email",
  "password": "password"
}

### Add Bill
POST https://autobilling.backend.vibevaulttech.co.in/addbill
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJiOWFhYmY5ZWNjZDVmNTcwOTNlYzAiLCJpYXQiOjE3Mjk5NDUwNDAsImV4cCI6MTcyOTk0NTA3MH0.rI9EMNjE3SsW-7IKlm85Q9kBMk7GdP0BL3jswZkTnXM

{
  "consumerName": "req.body.consumerName",
  "consumerEmail": "req.body.consumerEmail",
  "shopEmail": "req.body.shopEmail",
  "billAmount": "req.body.billAmount",
  "billDescription": "req.body.billDescription"
}

### Fetch Bill by Email
# POST https://autobilling.backend.vibevaulttech.co.in/fetchOrderByEmail
POST http://localhost:8000/fetchOrderByEmail
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJiOWFhYmY5ZWNjZDVmNTcwOTNlYzAiLCJpYXQiOjE3Mjk5NDUwNDAsImV4cCI6MTcyOTk0NTA3MH0.rI9EMNjE3SsW-7IKlm85Q9kBMk7GdP0BL3jswZkTnXM

{
  "shopEmail": "vaghleaohm@gmail.com"
}

### 
POST http://localhost:8000/sendEmail
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmJiOWFhYmY5ZWNjZDVmNTcwOTNlYzAiLCJpYXQiOjE3NDExOTk2MzMsImV4cCI6MTc0MTE5OTY2M30._B3ftZWUFwCEhJikjoyRNNlILSjxq1xcf7banth1Zr0

{
  "User":{
    "consumerEmail":"vaghelaohm@gmail.com",
    "_id":"66bc9628add10466ad8ad745"
  }
}

