apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  namespace: server
  name: http-to-https
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

