apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobilling-frontend
  namespace: client  
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: autobilling-client-pod
        image: ohmv10/autobilling-client:server.v1.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: autobilling-frontend-service
  namespace: client 
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
